// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdfxlyxfwtoukgrivfxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkZnhseXhmd3RvdWtncml2ZnhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMjg1MTksImV4cCI6MjA2MDgwNDUxOX0.KhIQGfJgroty8PNyFZEzJ8g2WtIf1C3Ht2ct6RpCN7c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);